Fix: TypeError: toFixed is not a function
The `toFixed()` method was being called on a non-numeric value.  This commit addresses the root cause of this error.